	<section class="home_slider">
		<div id="home_full_slider" class="rev_slider fullscreenbanner" data-version="5.3.1.6">
			<ul> 
				<?php for($i=0; $i<count($home_slider); $i++){ ?>
					<li data-index="<?php echo "rs-$i" ?>" data-transition="slotzoom-horizontal" data-slotamount="5" data-masterspeed="1000" data-fsmasterspeed="1000">
						<img src="<?php echo base_url(); ?>assets/img/home-slider/<?php echo $home_slider[$i]->image ?>" alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-bgparallax="10" data-no-retina>
						<div class="slider_text_box">
							<?php if(is_ar_lang()) {?>

								<div class="tp-caption tp-resizeme text_1" data-x="['right']" data-hoffset="['0','0','15','15','15']" data-y="['bottom']" data-voffset="['-10','0','0','0','0']" data-textAlign="['right']" data-fontsize="['70', '70','40','40','20']" data-lineheight="['100','100', '70','70','50']" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="y:[155%];x:0;z:0;rX:0deg;rY:0deg;rZ:0deg;sX:1;sY:1;skX:0;skY:0;s:1000;e:Power2.easeInOut;" data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-mask_in="x:10px;y:10px;s:inherit;e:inherit;" data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;" data-start="1500" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-elementdelay="0.05" style="font-family: 'DroidArabicKufiRegular', sans-serif; font-weight: 300; text-transform: uppercase;">
									<?php echo lang($home_slider[$i], 'title') ?>
								</div>
								<div class="tp-caption tp-shape tp-shapewrapper tp-resizeme line_1" data-x="['right']" data-hoffset="['0']" data-y="['top','top','top','top']" data-voffset="['-50']" data-width="2" data-height="5000px" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames='[{"from":"x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;","speed":1000,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"to":"opacity:0;","ease":"nothing"}]' data-textAlign="['right','right','right','right']" data-paddingtop="[10,10,10,10]" data-paddingleft="[0,0,0,0]" data-paddingbottom="[10,10,10,10]" data-paddingright="[0,0,0,0]" style="background-color:rgba(255, 255, 255, .10);"> </div>
								<div class="tp-caption tp-shape tp-shapewrapper tp-resizeme line_2" data-x="['right']" data-hoffset="['397']" data-y="['top','top','top','top']" data-voffset="['-50']" data-width="2" data-height="5000px" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames='[{"from":"x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;","speed":1000,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"to":"opacity:0;","ease":"nothing"}]' data-textAlign="['right','right','right','right']" data-paddingtop="[0,0,0,0]" data-paddingleft="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingright="[0,0,0,0]" style="background-color:rgba(255, 255, 255, .10);"> </div>
								<div class="tp-caption tp-shape tp-shapewrapper tp-resizeme line_3" data-x="['right']" data-hoffset="['795']" data-y="['top','top','top','top']" data-voffset="['-50']" data-width="2" data-height="5000px" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames='[{"from":"x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;","speed":1000,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"to":"opacity:0;","ease":"nothing"}]' data-textAlign="['right','right','right','right']" data-paddingtop="[0,0,0,0]" data-paddingleft="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingright="[0,0,0,0]" style="background-color:rgba(255, 255, 255, .10);"> </div>
								<div class="tp-caption tp-shape tp-shapewrapper tp-resizeme line_4" data-x="['right']" data-hoffset="['1168']" data-y="['top','top','top','top']" data-voffset="['-50']" data-width="2" data-height="5000px" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames='[{"from":"x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;","speed":1000,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"to":"opacity:0;","ease":"nothing"}]' data-textAlign="['right','right','right','right']" data-paddingtop="[0,0,0,0]" data-paddingleft="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingright="[0,0,0,0]" style="background-color:rgba(255, 255, 255, .10);"> </div>
								<div class="tp-caption tp-shape tp-shapewrapper tp-resizeme text_2" data-x="['right']" data-hoffset="['0','0','15','15','15']" data-y="['top','top','top','top']" data-voffset="['325','285','160','160','110']" data-width="86" data-height="6" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames='[{"from":"x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;","speed":1000,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"to":"opacity:0;","ease":"nothing"}]' data-textAlign="['right','right','right','right']" data-paddingtop="[0,0,0,0]" data-paddingleft="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingright="[0,0,0,0]" style="background-color:#231f20;"> </div>

								<div class="tp-caption tp-resizeme count" data-x="['right']" data-hoffset="['0','0','15','15','15']" data-y="['top']" data-voffset="['355','330','200','200','150']" data-textAlign="['right']" data-fontsize="['60', '60','60','60']" data-lineheight="['60','60', '60','60']" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="y:[155%];x:0;z:0;rX:0deg;rY:0deg;rZ:0deg;sX:1;sY:1;skX:0;skY:0;s:1000;e:Power2.easeInOut;" data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;" data-start="1000" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-elementdelay="0.05">
									<?php echo count($home_slider) . '/' .($i+1); ?>
								</div>
								<div class="tp-caption tp-resizeme text_3" data-x="['right']" data-hoffset="['0','0','15','15','15']" data-y="['bottom']" data-voffset="['240','240','240','240','170']" data-textAlign="['right']" data-fontsize="['18, 18, 20,22']" data-lineheight="['32','32', '32','32']" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="x:[-155%];z:0;rX:0deg;rY:0deg;rZ:0deg;sX:1;sY:1;skX:0;skY:0;s:2000;e:Power2.easeInOut;" data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;" data-start="1500" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-elementdelay="0.05" style="text-transform:uppercase;"><?php echo lang($home_slider[$i], 'desc'); ?>
							</div>
							<div class="tp-caption video" data-x="['left']" data-hoffset="['0','0','15']" data-y="[middle']" data-voffset="[-100']" data-textAlign="['center']" data-fontsize="['100', '100','100','100']" data-lineheight="['100','100', '100','100']" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="y:[-100%];x:0;z:0;rX:0deg;rY:0deg;rZ:0deg;sX:1;sY:1;skX:0;skY:0;s:1000;e:Power2.easeInOut;" data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;" data-start="2000" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-elementdelay="0.05"><a class="popup-with-move-anim" href="#small-dialog<?php echo $i; ?>"><img src="assets/img/icon/video-1.png" alt=""></a>
							<div id="small-dialog<?php echo $i; ?>" class="zoom-anim-dialog mfp-hide embed-responsive embed-responsive-16by9">
		                         <iframe width="1560" height="1315" src="<?php echo $home_slider[$i]->video; ?>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
	                        </div>
						</div>
						<?php } else {?>
							<div class="tp-caption tp-resizeme text_1" data-x="['left']" data-hoffset="['-5','0','15','15','15']" data-y="['bottom']" data-voffset="['-10','0','0','0','0']" data-textAlign="['left']" data-fontsize="['100', '100','70','70','50']" data-lineheight="['100','100', '70','70','50']" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="y:[155%];x:0;z:0;rX:0deg;rY:0deg;rZ:0deg;sX:1;sY:1;skX:0;skY:0;s:1000;e:Power2.easeInOut;" data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;" data-start="1500" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-elementdelay="0.05" style="font-family: 'Oswald', sans-serif; font-weight: 700; text-transform: uppercase;">
								<?php echo lang($home_slider[$i], 'title') ?>
							</div>
							<div class="tp-caption tp-shape tp-shapewrapper tp-resizeme line_1" data-x="['left']" data-hoffset="['0']" data-y="['top','top','top','top']" data-voffset="['-50']" data-width="2" data-height="5000px" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames='[{"from":"x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;","speed":1000,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"to":"opacity:0;","ease":"nothing"}]' data-textAlign="['left','left','left','left']" data-paddingtop="[10,10,10,10]" data-paddingright="[0,0,0,0]" data-paddingbottom="[10,10,10,10]" data-paddingleft="[0,0,0,0]" style="background-color:rgba(255, 255, 255, .10);"> </div>
							<div class="tp-caption tp-shape tp-shapewrapper tp-resizeme line_2" data-x="['left']" data-hoffset="['397']" data-y="['top','top','top','top']" data-voffset="['-50']" data-width="2" data-height="5000px" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames='[{"from":"x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;","speed":1000,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"to":"opacity:0;","ease":"nothing"}]' data-textAlign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="background-color:rgba(255, 255, 255, .10);"> </div>
							<div class="tp-caption tp-shape tp-shapewrapper tp-resizeme line_3" data-x="['left']" data-hoffset="['795']" data-y="['top','top','top','top']" data-voffset="['-50']" data-width="2" data-height="5000px" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames='[{"from":"x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;","speed":1000,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"to":"opacity:0;","ease":"nothing"}]' data-textAlign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="background-color:rgba(255, 255, 255, .10);"> </div>
							<div class="tp-caption tp-shape tp-shapewrapper tp-resizeme line_4" data-x="['left']" data-hoffset="['1168']" data-y="['top','top','top','top']" data-voffset="['-50']" data-width="2" data-height="5000px" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames='[{"from":"x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;","speed":1000,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"to":"opacity:0;","ease":"nothing"}]' data-textAlign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="background-color:rgba(255, 255, 255, .10);"> </div>
							<div class="tp-caption tp-shape tp-shapewrapper tp-resizeme text_2" data-x="['left']" data-hoffset="['0','0','15','15','15']" data-y="['top','top','top','top']" data-voffset="['325','285','160','160','110']" data-width="86" data-height="6" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames='[{"from":"x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;","speed":1000,"to":"o:1;","delay":500,"ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"to":"opacity:0;","ease":"nothing"}]' data-textAlign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="background-color:#231f20;"> </div>
							<div class="tp-caption tp-resizeme count" data-x="['left']" data-hoffset="['0','0','15','15','15']" data-y="['top']" data-voffset="['355','330','200','200','150']" data-textAlign="['left']" data-fontsize="['60', '60','60','60']" data-lineheight="['60','60', '60','60']" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="y:[155%];x:0;z:0;rX:0deg;rY:0deg;rZ:0deg;sX:1;sY:1;skX:0;skY:0;s:1000;e:Power2.easeInOut;" data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;" data-start="1000" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-elementdelay="0.05">
								<?php echo ($i+1) . '/' . count($home_slider); ?>
							</div>
							<div class="tp-caption tp-resizeme text_3" data-x="['left']" data-hoffset="['0','0','15','15','15']" data-y="['bottom']" data-voffset="['240','240','240','240','170']" data-textAlign="['left']" data-fontsize="['18, 18, 20,22']" data-lineheight="['32','32', '32','32']" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="x:[-155%];z:0;rX:0deg;rY:0deg;rZ:0deg;sX:1;sY:1;skX:0;skY:0;s:2000;e:Power2.easeInOut;" data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;" data-start="1500" data-splitin="chars" data-splitout="none" data-responsive_offset="on" data-elementdelay="0.05" style="letter-spacing:0.1em; text-transform:uppercase;">
								<?php echo lang($home_slider[$i], 'desc'); ?>
							</div>
							<div class="tp-caption video" data-x="['right']" data-hoffset="['0','0','15']" data-y="[middle']" data-voffset="[-100']" data-textAlign="['center']" data-fontsize="['100', '100','100','100']" data-lineheight="['100','100', '100','100']" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="y:[-100%];x:0;z:0;rX:0deg;rY:0deg;rZ:0deg;sX:1;sY:1;skX:0;skY:0;s:1000;e:Power2.easeInOut;" data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;" data-start="2000" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-elementdelay="0.05"><a class="popup-with-move-anim" href="#small-dialog<?php echo $i; ?>"><img src="assets/img/icon/video-1.png" alt=""></a>
							<div id="small-dialog<?php echo $i; ?>" class="zoom-anim-dialog mfp-hide embed-responsive embed-responsive-16by9">
		                        <iframe width="1560" height="1315" src="<?php echo $home_slider[$i]->video; ?>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
	                        </div>
						</div>
						<?php }?>
						
					</li>
				<?php } ?>
			</ul>
		</div>
		<div class="year">
			<a href="#">2018</a>
		</div>
		<div class="social_icon">
			<ul class="list">
				<li><a href="#"><i class="ion-social-twitter"></i></a></li>
				<li><a href="#"><i class="ion-social-facebook"></i></a></li>
				<li><a href="#"><i class="ion-social-googleplus"></i></a></li>
			</ul>
		</div>
	</section>
